packages/eslint-plugin/src/index.ts, packages/eslint-plugin/src/rules/no-pipe-impure.ts, packages/eslint-plugin/src/rules/prefer-on-push-component-change-detection.ts
Hey @sfabriece I'm sorry I forgot on my PR reviews to point out that the new rules need to be exported in order to be used, so they need to be added to: `packages/eslint-plugin/src/index.ts`
I also did a couple of minor refactorings that were not worth blocking the original PRs over - they now use the type guards available in utils rather than type assertions where possible
=> fix(eslint-plugin): expose new rules and use type guards

packages/eslint-plugin/src/index.ts, packages/eslint-plugin/src/rules/no-output-rename.ts, packages/eslint-plugin/tests/rules/no-output-rename.test.ts
This one was a bit more challenging than the previous rules. It might some refactoring.
=> feat(eslint-plugin): no output rename Rule

packages/builder/src/index.ts
Some users of nrwl/nx (nrwl/nx#2051) are requesting that `semi` not be a hard error while using eslint. 
This PR removes that rule before running the CLI Engine
=> fix(builder): remove `rule` section before running CLI engine

azure-pipelines.yml
Copied from: https://github.com/typescript-eslint/typescript-eslint/pull/1353
The js uploader keeps on timing out which causes coverage to not report, causing PR status to get stuck in pending.
The bash reporter has a retry mechanism, so it is supposed to be be more resilient.
=> test: use codecov bash uploader instead of js uploader

packages/eslint-plugin/src/index.ts, packages/eslint-plugin/src/rules/no-input-rename.ts, packages/eslint-plugin/src/rules/no-output-rename.ts, packages/eslint-plugin/src/utils/utils.ts, packages/eslint-plugin/tests/rules/no-input-rename.test.ts, packages/eslint-plugin/tests/rules/no-output-rename.test.ts
In addition to the original no-input-rename rule behavior of codelyzer, I added check for the names of setters.
Since the use of RegExp `/\p{L}\S*/gu` seems not necessary (at least the necessity is not obviously shown in the tests in codelyzer), I got rid of it.
I also made sure that `Input` is imported from `@angular/core` and also fixed `no-output-rename` rule accordingly.
=> feat(eslint-plugin): no-input-rename rule

package.json, packages/eslint-plugin-template/src/rules/no-negated-async.ts, packages/eslint-plugin-template/tests/rules/no-negated-async.test.ts, packages/eslint-plugin-template/tests/test-helper.ts, packages/integration-tests/fixtures/angular-cli-workspace/.eslintrc.js, packages/template-parser/src/index.ts, yarn.lock
Opening for visibility only right now.
@mgechev Do you know if there is any information/spec anywhere for how location information is applied to Angular Template AST nodes?
I have made progress on the `no-negated-async` rule here, but it's all through trial and error and I'm not very happy with it.
The use, and logic, of `sourceSpan` and `span` appears to be hard to predict, and inconsistent depending on hierarchies within the template.
E.g. the location data for a an async `BindingPipe` seems to change how it is given depending on whether or not an `Element` exists within its ancestors...
Please let me know if there are any resources in this area, or if I missed some existing utilities in the codelyzer codebase that could help with this!
=> feat(eslint-plugin-template): no-negated-async (with location issues)

packages/integration-tests/fixtures/angular-cli-workspace/.eslintrc.js
According to https://github.com/angular-eslint/angular-eslint/pull/51 `directive-class-suffix` is converted and no longer TODO
=> fix(integration-tests): uncomment converted rule

README.md, packages/eslint-plugin/src/index.ts, packages/eslint-plugin/src/rules/no-input-prefix.ts, packages/eslint-plugin/tests/rules/no-input-prefix.test.ts
Two small changes from the rule on Codelyzer:
- To be consistent with the message on the other rules, the error message is:
`@Inputs should not be prefixed by foo, bar` instead of `@Inputs should not be prefixed by "foo", or "bar"`
- The prefixes are configured on a `prefixes` object:
```
"@angular-eslint/no-input-prefix": ["error", {
prefixes: ['test'],
}],
```
Instead of being an array like on Codelyzer.
Please tell me if I should change something. This is my first PR so I am not sure of the preferred ways to do things here. 😄 
**References**
https://github.com/mgechev/codelyzer/blob/master/docs/rules/no-input-prefix/index.html
https://github.com/mgechev/codelyzer/blob/master/src/noInputPrefixRule.ts
---
Also, I think we may have an issue with Windows development. When I run `yarn …
=> feat(eslint-plugin): add no-input-prefix rule

packages/builder/src/index.ts, packages/builder/src/schema.json
Related to #26 
**Behavior**
- If ignorePath is not set on `angular.json` and `.eslintignore` does exists, the linter will proceed as usual
- If ignorePath is not set on `angular.json` but `.eslintignore` exists, then the files mentioned on the file will be ignored
- If ignorePath is set on `angular.json` then the custom ignore file will be used instead of `.eslintignore`, note that this file must exist or eslint will throw an error, even if you set as `.eslintignore`
**Considerations**
- Should I add tests on `integration-tests`?
- The name of the option on eslint is `ignorePath`, I personally find it kinda confusing but decided to keep it since changing could cause other types of confusion...
=> feat(builder): add ignorePath option

README.md
I upgraded my Angular Dev environment from 7 to 9 earlier this week and I moved from TSLint to ESLint at the same time.  I had some Codelyzer rules that need the eslint rule that converts tslint rules to eslint rules.  That package requires a specific parser that parser is not compatible with the template rules in this project.
It took me too long (I nearly gave up) to figure out the correct config to get your amazing project to work correctly.  I believe if this snippet (which I took from your own source code) is added to your main doc then it will help others start using your project more quickly and easily.  Hope you agree.
=> docs: add an example config to main docs for template linting

packages/builder/src/index.ts
Fix to allow eslint major versions greater than 6. Current logic only allows eslint major version 6.
=> fix(builder): allow latest eslint

packages/eslint-plugin-template/src/configs/all.json, packages/eslint-plugin-template/src/configs/recommended.json, packages/eslint-plugin-template/src/index.ts, packages/eslint-plugin-template/src/rules/banana-in-box.ts, packages/eslint-plugin-template/tests/rules/banana-in-box.test.ts, packages/integration-tests/tests/__snapshots__/integration.ts.snap, tools/scripts/generate-rules-list/generate-rules-list.ts
As stated in #134: Rename `banana-in-a-box` to `banana-in-box` to conform with:
1. [Codelyzer rule](http://codelyzer.com/rules/template-banana-in-box/) name
1. Rule [generated by `tslint-to-eslint-config`](https://github.com/typescript-eslint/tslint-to-eslint-config#usage)
=> fix(eslint-plugin-template): rename banana-in-a-box to banana-in-box

packages/eslint-plugin/src/rules/no-empty-lifecycle-method.ts
Closes #181 
Closes #188 
Changes the message for the `no-empty-lifecycle-method` rule from
`Declaring {{methodName}} lifecycle method in a class is not recommended`
to
`Lifecycle method {{methodName}} should not be empty`
=> fix(eslint-plugin): incorrect message for no-empty-lifecycle-method

packages/eslint-plugin-template/src/processors.ts, packages/eslint-plugin-template/tests/processors.test.ts
Fixes https://github.com/angular-eslint/angular-eslint/issues/185
> > I haven't been able to compile the full source yet
> 
> I'm not sure what you mean by this
I couldn't get `npm run build` in `/packages/eslint-plugin-template` working the other week for some reason... Today it worked and I manually verified that the compiled/build package with the fix works in my other project.
=> fix: components with inline templates and CRLF

README.md
=> Fix: docs typo

README.md, packages/eslint-plugin-template/src/configs/all.json, packages/eslint-plugin-template/src/index.ts, packages/eslint-plugin-template/tests/configs.test.ts, packages/eslint-plugin/tests/configs.test.ts
Fixes https://github.com/angular-eslint/angular-eslint/issues/247. This:
- Adds `no-any` to the exported rules, as it was missing in https://github.com/angular-eslint/angular-eslint/pull/205
- Sorts the imports & exported rules to clean things up
- Fix the `eslint-plugin` & `eslint-plugin-template` config tests as those were broken (missing `.toBeTrue(true)` assertion)
- Adds `@angular-eslint/template/use-track-by-function` to the `all` config as this was caught by the fixed tests, and sort the rules as well
- Extends the `eslint-plugin` & `eslint-plugin-template` config tests to catch similar issues to https://github.com/angular-eslint/angular-eslint/issues/247, i.e. rules added in the configs but not exported from the configs. For simplicity only the config `rules` entry is currently …
=> fix(*): export no-any rule, fix & improve config tests

packages/eslint-plugin-template/src/rules/accessibility-elements-content.ts, packages/eslint-plugin-template/tests/rules/accessibility-elements-content.test.ts
**Current behavior**:
We can pass html content by using `innerHTML` and `innerHtml`. The later isn't currently ignored by the rule.
```html
<h3 [innerHtml]="dangerouslySetHTML"></h3>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
**Expected behavior**:
```html
<h3 [innerHtml]="dangerouslySetHTML"></h3> // Pass
```
<hr>
I also replaced conditionals by selectors to make it more readable and shorter.
=> fix(eslint-plugin-template): handle 'innerHtml' input properly

README.md, packages/integration-tests/local-registry/config.yml, packages/integration-tests/package.json, yarn.lock
Trying to combat integration test install flakiness by implementing the suggestions from: https://github.com/verdaccio/verdaccio/discussions/2038
I needed to regenerate the README because there are open rule PRs
=> chore: update verdaccio version and config

.github/workflows/ci.yml, README.md
Temporarily pinning to 15.4 for the v15 installation because there is some change in NPM that causes a ENEEDAUTH error in the publishing step of the integration-tests that needs to be figured out.
It could be caused by: https://github.com/npm/cli/issues/2411, but needs more investigation, I want to unblock us for now as the priority
=> chore: temporarily pin node 15 to 15.4

packages/eslint-plugin/src/rules/contextual-decorator.ts, packages/eslint-plugin/src/rules/contextual-lifecycle.ts, packages/eslint-plugin/src/rules/no-empty-lifecycle-method.ts, packages/eslint-plugin/src/rules/no-lifecycle-call.ts, packages/eslint-plugin/src/rules/use-lifecycle-interface.ts, packages/eslint-plugin/src/utils/utils.ts, packages/eslint-plugin/tests/rules/contextual-lifecycle.test.ts, packages/eslint-plugin/tests/rules/no-empty-lifecycle-method.test.ts, packages/eslint-plugin/tests/rules/no-lifecycle-call.test.ts, packages/eslint-plugin/tests/rules/use-lifecycle-interface.test.ts, packages/integration-tests/tests/__snapshots__/v1014-multi-project-manual-config.test.ts.snap, packages/integration-tests/tests/__snapshots__/v11-new-workspace.test.ts.snap
This:
- Handles `DoBootstrap`/`ngDoBootstrap` for all 4 lifecycle rules correctly now;
- `no-empty-lifecycle-method` handles all decorators. Before it was caring only about `Component` and `Directive`;
- `no-empty-lifecycle -method` now ignores non-angular classes;
- `use-lifecycle-interface` now ignores non-angular classes.
=> fix(eslint-plugin): handle DoBootstrap correctly in lifecycle rules

README.md, packages/eslint-plugin-template/src/configs/all.json, packages/eslint-plugin-template/src/index.ts, packages/eslint-plugin-template/src/rules/accessibility-label-for.ts, packages/eslint-plugin-template/src/utils/is-child-node-of.ts, packages/eslint-plugin-template/tests/rules/accessibility-label-for.test.ts
As soon as I started this implementation, I noticed that [the current version in Codelyzer](https://github.com/mgechev/codelyzer/blob/master/src/templateAccessibilityLabelForRule.ts) has some problems:
1. It doesn't report labels without association, e.g.:
```html
<label for="nonExistentId">Label</label>
```
2. One could pass control component selectors through the `controlComponents` option, like this:
```json
"template-accessibility-label-for": [true, {
"controlComponents": ["p-inputMask"],  
}]
```
```html
<app-label labelFor="username">Label<p-inputMask></p-inputMask></app-label>
```
...however one could have a component with an attribute that acts like an `id`, like [the `inputId` here, by example](https://www.primefaces.org/primeng/showcase/#/inputmask) and thus doesn't need to be …
=> feat(eslint-plugin-template): accessibility-label-for

.github/FUNDING.yml, packages/eslint-plugin-template/src/rules/conditional-complexity.ts, packages/eslint-plugin-template/src/utils/create-eslint-rule.ts, packages/eslint-plugin-template/tests/rules/conditional-complexity.test.ts
This PR aims to fix the cases:
- report when using any other bound attribute besides `ngIf`, which is the only one currently reported;
- *report when using a `Pipe` as the last statement in a condition;
- report when using `Conditional`;
- report when using `Interpolation`;
This also removes some duplicate unit tests and include `data` to ensure the complexity is computed correctly.
*: This case was reported in #280 (**case 3**) and is partially fixed here, because it was fixed only when it appears as the last statement in a condition. To completely fix it, further investigation will be required and will take some more time and probably better to do in another PR.
=> fix(eslint-plugin-template): conditional-complexity not reporting all cases

packages/eslint-plugin/docs/rules/component-class-suffix.md
Docs for rule [component-class-sufix](https://github.com/angular-eslint/angular-eslint/blob/master/packages/eslint-plugin/src/rules/component-class-suffix.ts), in accordance to the effort for documentation #197
=> docs: Created docs for rule 'component-class-suffix'

README.md
Add missing colon so it does not error when you copy the example.
=> fix: Add missing colon

packages/eslint-plugin/src/rules/no-lifecycle-call.ts, packages/eslint-plugin/src/utils/utils.ts, packages/eslint-plugin/tests/rules/no-lifecycle-call.test.ts
**First commit**: Adds a method to find the nearest node based on the received node.
**Second commit**: This clean up the huge amount of tests I noticed in https://github.com/angular-eslint/angular-eslint/pull/243#issuecomment-749695110 (most of them copied from `contextual-lifecycle`).
**Third commit**: Fixes #246, before this commit this rule didn't report any `super <lifecycle method>()`, regardless of the context and also reports any class, even if the class isn't decorated by Angular decorators. Now it may be fixed.
=> fix(eslint-plugin): no-lifecycle-call invalid super calls not being reported

packages/eslint-plugin-template/src/configs/all.json, packages/eslint-plugin-template/src/index.ts, packages/eslint-plugin-template/src/rules/no-duplicate-attributes.ts, packages/eslint-plugin-template/tests/rules/no-duplicate-attributes.test.ts
This PR implements the rule suggested in https://github.com/angular-eslint/angular-eslint/issues/293. This was my first time writing an eslint rule, so apologies if I made any silly mistakes 😄 It was a _really_ nice codebase to contribute to with lots of examples so hopefully there is nothing too bad in there. I tried to highlight the things I wasn't sure about, please let me know if you'd like me to make any changes! 😄
=> feat(eslint-plugin-template): add no duplicate attributes rule

packages/eslint-plugin/src/rules/component-max-inline-declarations.ts, packages/eslint-plugin/tests/rules/component-max-inline-declarations.test.ts
While working on a fix for #304, I noticed that we could clean up this rule/tests, and so I did. Here's the context of each commit:
**First commit**: Currently we perform some checks to verify that the received limit is > `-1`. Now, we rely on the schema that can handle it automatically.
**Second commit**: Currently we use the function `getDecoratorPropertyValue` to get the desired property. Now, we use selectors instead.
**Third commit**: The tests are a bit verbose with a lot of annotations and also we don't check if the lines are calculated properly. With this commit, we have cleaner tests with properties checking through `data`.
**Fourth commit**: Fixes #304, before this commit we were calculating animation lines as `string`, however it isn't. Now, it may be checked properly.
=> fix(eslint-plugin): component-max-inline-declarations animations not being checked properly 

packages/template-parser/src/index.ts
Added `BindingPipe: ['exp']` to `template-parser` for (#337)
=> fix(template-parser): add BindingPipe exp to VisitorKeys (#337)

packages/builder/src/index.ts, packages/builder/src/schema.d.ts, packages/builder/src/schema.json, packages/builder/tests/index.test.ts
Implements [ESLint's max-warnings CLI option](https://eslint.org/docs/user-guide/command-line-interface#:~:text=quiet%20file.js-,%2D%2Dmax%2Dwarnings,with%20a%20success%20exit%20status.).
When migrating from TSLint to ESLint recently, we wanted to show linting errors only as warnings during development in vscode (as the TSLint extension does), but at the same time we also use the ng lint command in our CI and want to fail on these warnings.
At first, I thought about a `--strict` flag, but after reading [this ESLint thread](https://github.com/eslint/eslint/issues/2309), it looked best to just implement the max-warnings flag.
=> feat(builder): add maxWarnings option

README.md
Codelyzer is added by default to every Angular project. Some people who migrate their Angular project to ESLint might not know that `codelyzer` can be removed after removing TSLint. So I thought it would be better to suggest removing it in the README.
=> Suggest removal of codelyzer in README

packages/eslint-plugin/src/rules/no-attribute-decorator.ts, packages/eslint-plugin/tests/rules/no-attribute-decorator.test.ts
This PR changes the implementation of `no-attribute-decorator` to use selectors. In addition, I removed some unnecessary tests and still kept 100% coverage.
=> refactor(eslint-plugin): no-attribute-decorator switch to selectors

packages/eslint-plugin-template/src/rules/accessibility-elements-content.ts, packages/eslint-plugin-template/src/utils/is-hidden-from-screen-reader.ts, packages/eslint-plugin-template/tests/rules/accessibility-elements-content.test.ts, packages/eslint-plugin-template/tests/rules/click-events-have-key-events.test.ts
**1st. commit**: with this `isHiddenFromScreenReader` now returns `true` for empty `aria-hidden`, e.g.: `<div aria-hidden></div>`;
**2nd. commit**: with this `accessibility-elements-content` now ignores elements when the attributes `aria-hidden`, `aria-label`, `outerHTML` and `title` are present.
Btw, part of this fix was reported in https://github.com/mgechev/codelyzer/issues/993.
It's also related to https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/423 and its proposed fix https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/727
=> fix(eslint-plugin-template): accessibility-elements-content not allowing some attributes/inputs

packages/builder/src/schema.json
Currently (v2.0.2), when running `ng lint --max-warnings=0`, the CLI throws
Unknown option: '--max-warnings'
It turns out the `schema.json` file declares `maxWarnings` as an `integer` instead of a `number` as the CLI expects.
See https://github.com/angular/angular-cli/blob/645353db26e9d6e8f893322a52b320ccd5ca1d5d/packages/angular_devkit/build_angular/src/browser/schema.json#L258 for example
After this fix, the option is usable.
=> fix(builder): expose maxWarnings option

packages/eslint-plugin/src/rules/directive-class-suffix.ts, packages/eslint-plugin/src/rules/pipe-prefix.ts, packages/eslint-plugin/src/utils/utils.ts, packages/eslint-plugin/tests/rules/directive-class-suffix.test.ts
1st. commit is the fix for #353.
2nd. commit is a refactor that:
- makes report message more-friendly;
- removes unnecessary tests and uses `data` property to ensure we pass the correct parameters to the user.
In any case, if you prefer, I could split it into 2 PRs.
Fixes #353.
=> fix(eslint-plugin): directive-class-suffix reporting selectorless directives

packages/eslint-plugin/src/rules/sort-ngmodule-metadata-arrays.ts, packages/eslint-plugin/tests/rules/sort-ngmodule-metadata-arrays.test.ts
The problem is that `undefined` is not treated properly and thus some values are flagged incorrectly.
Fixes #407.
=> fix(eslint-plugin): `sort-ngmodule-metadata-arrays` reporting false positives

packages/schematics/package.json, packages/schematics/src/convert-tslint-to-eslint/convert-to-eslint-config.ts, packages/schematics/src/convert-tslint-to-eslint/index.ts, packages/schematics/src/migrations/update-2-0-0/update-2-0-0.ts, packages/schematics/src/migrations/update-3-0-0/update-3-0-0.ts, packages/schematics/src/utils.ts, packages/schematics/tests/convert-tslint-to-eslint/convert-to-eslint-config.test.ts, yarn.lock
Refactors the internals of schematics to make a few improvements:
- `tslint-to-eslint-config` is no longer a static dependency of the schematics package, meaning that TSLint no longer is either, so users will no longer see warnings about it being deprecated as part of `ng add`
- Bumps the version and slightly expands the range of `tslint-to-eslint-config` (Fixes #344)
- when iterating through the files in the `Tree` as part of a conversion it now takes `.gitignore` data into account
=> feat(schematics): dynamically install tslint-to-eslint-config as needed

packages/eslint-plugin-template/src/rules/i18n.ts, packages/eslint-plugin-template/tests/rules/i18n.test.ts
After some recent fixes I applied to this rule, I realized that it was a little difficult to read, fix bugs and also implement new features. That said, I decided to refactor it. This PR doesn't bring functional changes, that is, everything should work as it currently does.
- The first commit is just a cleanup in tests, removing unnecessary attributes, formatting and include data to ensure the `attributeName` is correctly passed.
- The second commit is the proposed changes to the rule in the hope of making this a little more readable and maintainable.
=> refactor(eslint-plugin-template): [i18n] refactor to improve readability and maintainability

packages/eslint-plugin-template/src/rules/no-call-expression.ts, packages/template-parser/src/index.ts
When working on #444, I realized that this key was missing and it was a little difficult to make the rules work correctly without a lot of effort.
=> fix(template-parser): add missing `Conditional` and its keys to `VisitorKeys`

packages/eslint-plugin-template/src/rules/no-negated-async.ts, packages/eslint-plugin-template/tests/rules/no-negated-async.test.ts
BREAKING CHANGE.
Currently it's a proposal. If it gets approved, we could implement a rule to perform equality checks.
Fixes #315.
=> refactor(eslint-plugin-template): no-negated-async no longer perform equality checks

packages/eslint-plugin/src/rules/relative-url-prefix.ts, packages/eslint-plugin/tests/rules/relative-url-prefix.test.ts
Fixes #334.
In addition, it no longer reports urls as:
- './../foobar.css'
- '.././foobar.html'
=> fix(eslint-plugin): [relative-url-prefix] valid relative urls being reported

packages/eslint-plugin/src/rules/no-empty-lifecycle-method.ts, packages/eslint-plugin/tests/rules/no-empty-lifecycle-method.test.ts
Similar to what we did in #314, it cleans up the huge amount of unnecessary tests I noticed in https://github.com/angular-eslint/angular-eslint/pull/243#issuecomment-749695110 (most of them copied from contextual-lifecycle).
=> test(eslint-plugin): [no-empty-lifecycle] clean up tests

packages/eslint-plugin-template/src/rules/no-negated-async.ts, packages/eslint-plugin-template/tests/rules/no-negated-async.test.ts
=> fix(eslint-plugin-template): [no-negated-async] ignore double-bang

packages/eslint-plugin/src/rules/prefer-output-readonly.ts, packages/eslint-plugin/tests/rules/prefer-output-readonly.test.ts
To be reviewed after #458's merge.
Note that I went with a `suggest` instead of `fix`, because if we fix it directly we can break the code since there is no guarantee that `@Output` property is not being mutated somewhere.
=> feat(eslint-plugin): [prefer-output-readonly] add suggestion

packages/eslint-plugin-template/src/rules/eqeqeq.ts, packages/eslint-plugin-template/tests/rules/eqeqeq.test.ts
Change the fix to a suggest as we can't guarantee that the replace is safe without type information (except for cases where plain string is being compared, such as "apple", "null", etc).
=> fix(eslint-plugin-template): [eqeqeq] change fix to suggest

README.md, packages/template-parser/src/index.ts, packages/template-parser/tests/index.test.ts
=> fix(template-parser): generate correct index.d.ts when building

packages/eslint-plugin/src/rules/no-host-metadata-property.ts, packages/eslint-plugin/src/utils/utils.ts, packages/eslint-plugin/tests/rules/no-host-metadata-property.test.ts
With this:
- `computed` properties are now reported (even with `allowStatic` option enabled) as we can't guarantee that it refers to a static value;
- when `host` is `shorthand` the rule doesn't crash anymore;
- it doesn't report empty string values anymore like `'[@routerTransition]': ''` because IMO it can be considered static, no?
**Reference**:
https://github.com/mgechev/codelyzer/issues/393
https://github.com/angular/angular/issues/19110
=> fix(eslint-plugin): [no-host-metadata-property] correct false positive with `allowStatic` option

packages/eslint-plugin/src/rules/no-output-on-prefix.ts, packages/eslint-plugin/src/utils/selectors.ts, packages/eslint-plugin/tests/rules/no-output-on-prefix.test.ts, packages/integration-tests/tests/__snapshots__/v1123-multi-project-manual-config.test.ts.snap
With this PR, `alias` like `onChange` in `@Output('onChange') test = new EventEmitter<void>();` are correctly reported.
=> fix(eslint-plugin): [no-output-on-prefix] not reporting failures on alias

packages/eslint-plugin-template/src/rules/no-negated-async.ts, packages/eslint-plugin-template/tests/rules/no-negated-async.test.ts
Similar to [**`@typescript-eslint/no-explicit-any`**](https://github.com/typescript-eslint/typescript-eslint/blob/1c1b572c3000d72cfe665b7afbada0ec415e7855/packages/eslint-plugin/src/rules/no-explicit-any.ts), this PR adds three possible suggestions to offer a practical way to fix the report.
=> feat(eslint-plugin-template): [no-negated-async] add suggestion

packages/integration-tests/tests/__snapshots__/v12-new-workspace.test.ts.snap, packages/schematics/src/convert-tslint-to-eslint/index.ts, packages/schematics/src/utils.ts, packages/schematics/tests/add-eslint-to-project/index.test.ts, packages/schematics/tests/application/index.test.ts, packages/schematics/tests/library/index.test.ts
fix #453 
The pr contains the change to determine if the project contains e2e content by checking for the presence of e2e architect in the `angular.json`, then skip adding e2e's tsconfig to`parserOptions.projects` if the target project is a non-e2e project.
=> fix(schematics): skip e2e tsconfig for add to non e2e project

packages/schematics/src/convert-tslint-to-eslint/convert-to-eslint-config.ts, packages/schematics/src/convert-tslint-to-eslint/index.ts, packages/schematics/src/convert-tslint-to-eslint/utils.ts, packages/schematics/src/library/index.ts, packages/schematics/src/migrations/update-2-0-0/update-2-0-0.ts, packages/schematics/src/migrations/update-3-0-0/update-3-0-0.ts, packages/schematics/src/migrations/update-4-0-0/update-4-0-0.ts, packages/schematics/src/ng-add/index.ts, packages/schematics/src/utils.ts
Unfortunately `eslint-disable *` is the most viable solution in most cases here, because if we try to modify the types, it breaks in many places with difficult solutions.
=> refactor(schematics): suppress lint warnings

packages/eslint-plugin/src/rules/contextual-decorator.ts, packages/eslint-plugin/src/rules/use-pipe-transform-interface.ts, packages/eslint-plugin/src/utils/utils.ts, packages/eslint-plugin/tests/rules/use-pipe-transform-interface.test.ts
1st commit: Moves some utility functions from `contextual-decorator` and `use-pipe-transform-interface` to `utils/ ` package so we can reuse it for `imports` and `implements`;
2nd commit: A simple test addition to ensure we target the correct import in fix when there are multiple imports from the same source.
=> refactor: move utility functions to utils package

package.json, packages/builder/src/schema.d.ts, packages/builder/src/schema.json, packages/builder/src/utils/eslint-utils.ts, packages/builder/tests/index.test.ts, packages/builder/tests/utils/eslint-utils.test.ts, yarn.lock
Closes #410.
~Waiting for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53485.~
=> feat(builder): add `cacheStrategy` option

packages/eslint-plugin-template/src/rules/eqeqeq.ts, packages/eslint-plugin-template/src/utils/get-nearest-node-from.ts, packages/eslint-plugin/src/rules/no-empty-lifecycle-method.ts, packages/eslint-plugin/src/rules/no-lifecycle-call.ts, packages/eslint-plugin/src/utils/utils.ts
Currently, if it isn't possible to determine a fix in utility functions, we simply return an empty `array` (`TSESLint.RuleFix[]`) and this can be a little confuse, as we need to encapsulate the fixers in `arrays` and use `.concat` (which accepts either a single item or an `array`). See https://github.com/angular-eslint/angular-eslint/pull/501#discussion_r641589200.
In this PR, the proposal is to return `undefined` instead and whenever we use it in `report#fix` (which accepts `IterableIterator<RuleFix> | TSESLint.RuleFix | TSESLint.RuleFix[] | null`), we call the` isNotNullOrUndefined` helper to extract only the _non-undefined_ fixes from the `array` and make the compiler happy.
=> refactor(utils): change return type of fixer utilities

.eslintrc.json, packages/builder/tests/index.test.ts, packages/eslint-plugin/src/rules/contextual-decorator.ts, packages/eslint-plugin/src/rules/contextual-lifecycle.ts, packages/eslint-plugin/src/rules/no-conflicting-lifecycle.ts, packages/eslint-plugin/src/rules/no-host-metadata-property.ts, packages/eslint-plugin/src/rules/no-input-rename.ts, packages/eslint-plugin/src/rules/no-lifecycle-call.ts, packages/eslint-plugin/src/rules/no-output-rename.ts, packages/eslint-plugin/src/rules/prefer-on-push-component-change-detection.ts, packages/eslint-plugin/src/rules/sort-ngmodule-metadata-arrays.ts, packages/eslint-plugin/src/rules/use-lifecycle-interface.ts, packages/eslint-plugin/src/utils/create-eslint-rule.ts, packages/eslint-plugin/src/utils/property-selector.ts, packages/eslint-plugin/src/utils/utils.ts
1st. commit: add a pattern to ignore vars starting with `_` to suppress some cases we have in repo, like `_ruleName`, `_fileName`;
2nd. commit: add the rule `array-type` that standarize the array type to be used;
3rd. commit: use `AST_NODE_TYPES` enum instead of plain strings in `utils`;
4th. commit: suppress lint warnings, remove some typecasts, remove null-assertions, adjust some typings and use type guard functions for better inference.
~**WIP**: Waiting for the resolution of the related PRs~.
=> refactor(eslint-plugin): suppress lint warnings and better typings

packages/eslint-plugin/src/rules/no-output-on-prefix.ts, packages/eslint-plugin/tests/rules/no-output-on-prefix.test.ts, packages/integration-tests/tests/__snapshots__/v1123-multi-project-manual-config.test.ts.snap
This PR basically fixes the same problems related in #523, but for `no-output-on-prefix`.
@JamesHenry while doing this I just noticed that we aren't checking the `outputs` metadata property. Example:
```ts
@Component({
outputs: ['onChange'],
})
class Test {}
```
Should we support it here and in other `*-output-*` rules? If so, I can work on this on another PRs.
=> fix(eslint-plugin): [no-output-on-prefix] correct false positives

packages/eslint-plugin/src/rules/prefer-output-readonly.ts, packages/eslint-plugin/tests/rules/prefer-output-readonly.test.ts
A minor refactor to make use of the shared selector `OUTPUT_DECORATOR`. I also took the opportunity to add a test to make sure it only reports properties with the expected decorator.
=> refactor(eslint-plugin): [prefer-output-readonly] use computed selector

packages/eslint-plugin/src/rules/no-outputs-metadata-property.ts, packages/eslint-plugin/tests/rules/no-outputs-metadata-property.test.ts, packages/integration-tests/tests/__snapshots__/v1123-multi-project-manual-config.test.ts.snap
Basically changes the implementation to use selectors. In addition to this, I added some tests to ensure we only report non-computed properties.
=> refactor(eslint-plugin): [no-outputs-metadata-property] switch to selectors

packages/eslint-plugin/src/rules/no-output-on-prefix.ts, packages/eslint-plugin/tests/rules/no-output-on-prefix.test.ts, packages/integration-tests/tests/__snapshots__/v1123-multi-project-manual-config.test.ts.snap
This PR implements the checks for both `getters` and `outputs` metadata property for `no-output-on-prefix` rule.
=> fix(eslint-plugin): [no-output-on-prefix] handle `getters` and `outputs` metadata property

packages/eslint-plugin/src/rules/no-pipe-impure.ts, packages/eslint-plugin/tests/rules/no-pipe-impure.test.ts
Besides it adds the suggestion to remove the `pure` property, it:
- ignores computed properties;
- reports `Literal` properties correctly;
- reports `UnaryExpression` correctly.
=> feat(eslint-plugin): [no-pipe-impure] add suggestion

packages/eslint-plugin/src/rules/no-input-prefix.ts, packages/eslint-plugin/src/utils/selectors.ts, packages/eslint-plugin/src/utils/utils.ts, packages/eslint-plugin/tests/rules/no-input-prefix.test.ts
Following the same we did in #566, this PR implements the checks for both alias and `inputs` metadata property for `no-input-prefix` rule.
=> fix(eslint-plugin): [no-input-prefix] handle alias and `inputs` metadata property

packages/eslint-plugin/src/rules/no-input-rename.ts, packages/eslint-plugin/src/utils/get-aria-attribute-keys.ts, packages/eslint-plugin/src/utils/selectors.ts, packages/eslint-plugin/src/utils/utils.ts, packages/eslint-plugin/tests/rules/no-input-rename.test.ts
Following the same we did in #568, this PR implements the checks for both alias and `inputs` metadata property for `no-input-rename` rule.
In addittion to this, I've added suggestion and fix (in case of property name === alias name).
=> fix(eslint-plugin): [no-input-rename] handle alias and `inputs` metadata property

packages/eslint-plugin/src/rules/no-inputs-metadata-property.ts, packages/eslint-plugin/src/utils/selectors.ts, packages/eslint-plugin/tests/rules/no-inputs-metadata-property.test.ts, packages/eslint-plugin/tests/rules/no-pipe-impure.test.ts, packages/integration-tests/tests/__snapshots__/v1123-multi-project-manual-config.test.ts.snap
Basically changes the implementation to use selectors. In addition to this, I added some tests to ensure we only report non-computed properties.
=> refactor(eslint-plugin): [no-inputs-metadata-property] switch to selectors

packages/eslint-plugin/src/rules/use-pipe-transform-interface.ts, packages/eslint-plugin/src/utils/utils.ts, packages/eslint-plugin/tests/rules/use-pipe-transform-interface.test.ts
This PR aims to fix a problem with import duplication in `fix`.
If we have an import `type` statement, the `fix` ignores it and duplicate `PipeTransform` in a common import statement.
=> fix(eslint-plugin): [use-pipe-transform-interface] handle type imports properly in fix

packages/eslint-plugin/src/rules/no-inputs-metadata-property.ts, packages/eslint-plugin/src/rules/no-output-native.ts, packages/eslint-plugin/src/rules/no-output-on-prefix.ts, packages/eslint-plugin/src/rules/no-output-rename.ts, packages/eslint-plugin/src/rules/no-outputs-metadata-property.ts, packages/eslint-plugin/src/utils/selectors.ts, packages/eslint-plugin/tests/rules/no-output-native.test.ts, packages/eslint-plugin/tests/rules/no-output-on-prefix.test.ts, packages/eslint-plugin/tests/rules/no-output-rename.test.ts, packages/eslint-plugin/tests/rules/no-outputs-metadata-property.test.ts
I completely forgot to add support for literal `'outputs'` (and also in others 😢) in the previous PRs. Now, properties like these are reported:
```ts
@Component({ 'outputs': [...] })
class Test {}
@Component({ ['outputs']: [...] })
class Test {}
@Component({ [`outputs`]: [...] })
class Test {}
```
PS: As it's a small change I chose to create a single PR with separated commits for each rule... but, if necessary, I can open separated PRs.
=> fix(eslint-plugin): handle literal `outputs` properly for [*-output-*] rules

packages/eslint-plugin/docs/rules/use-injectable-provided-in.md, packages/eslint-plugin/src/rules/use-injectable-provided-in.ts, packages/eslint-plugin/src/utils/selectors.ts, packages/eslint-plugin/src/utils/utils.ts, packages/eslint-plugin/tests/rules/use-injectable-provided-in/cases.ts
**1st. commit**: adds suggestions that covers the most common values and also fixes some false negatives like when we use `null` as value or when we use a computed argument to `@Injectable` decorator and false positives when we use `'providedIn'` as a `Literal`;
**2nd. commit**: ignore classes that implements `HttpInterceptor` (see #236);
**3rd. commit**: add option to ignore classes given a pattern (see #236).
Closes #236.
=> feat(eslint-plugin): [use-injectable-provided-in] add suggestion

packages/eslint-plugin/docs/rules/no-input-prefix.md, packages/eslint-plugin/docs/rules/no-input-rename.md, packages/eslint-plugin/docs/rules/no-inputs-metadata-property.md, packages/eslint-plugin/docs/rules/no-pipe-impure.md, packages/eslint-plugin/docs/rules/use-component-view-encapsulation.md, packages/eslint-plugin/src/rules/no-inputs-metadata-property.ts, packages/eslint-plugin/src/rules/no-pipe-impure.ts, packages/eslint-plugin/src/rules/use-component-view-encapsulation.ts, packages/eslint-plugin/tests/rules/no-input-prefix/cases.ts, packages/eslint-plugin/tests/rules/no-input-rename/cases.ts, packages/eslint-plugin/tests/rules/no-inputs-metadata-property/cases.ts, packages/eslint-plugin/tests/rules/no-pipe-impure/cases.ts, packages/eslint-plugin/tests/rules/use-component-view-encapsulation/cases.ts
With this, computed literals are now reported in the following rules:
- `no-inputs-metadata-property`;
- `no-input-prefix`;
- `no-input-rename`;
- `no-pipe-impure`;
- `use-view-encapsulation`.
=> fix(eslint-plugin): properly handle computed literals for some rules

packages/eslint-plugin-template/docs/rules/no-call-expression.md, packages/eslint-plugin-template/src/rules/no-call-expression.ts, packages/eslint-plugin-template/tests/rules/no-call-expression/cases.ts
This PR aims to correct report `FunctionCall`s in `no-call-expression`, e.g.:
```html
<div>{{ getInfo()() }}</div>
<a [href]="test()()">info</a>
```
=> fix(eslint-plugin-template): [no-call-expression]: `FunctionCall`s not being reported

packages/eslint-plugin/docs/rules/no-empty-lifecycle-method.md, packages/eslint-plugin/src/rules/no-conflicting-lifecycle.ts, packages/eslint-plugin/src/rules/no-empty-lifecycle-method.ts, packages/eslint-plugin/src/utils/selectors.ts, packages/eslint-plugin/src/utils/utils.ts, packages/eslint-plugin/tests/rules/no-empty-lifecycle-method/cases.ts
In addittion to the fix on suggestion, it now reports literal `MethodDefinition`s and removes interfaces within `MemberExpression`s.
Fixes #604.
=> fix(eslint-plugin): [no-empty-lifecycle-method] incorrect suggestions and correct reports

packages/eslint-plugin/docs/rules/sort-ngmodule-metadata-arrays.md, packages/eslint-plugin/src/rules/sort-ngmodule-metadata-arrays.ts, packages/eslint-plugin/tests/rules/sort-ngmodule-metadata-arrays/cases.ts
This adds supports for computed properties and literals, like:
- `[providers]: [...]`
- `'imports': [...]`
- `['schema']: [...]`
- `[``declarations``]: [...]`
=> fix(eslint-plugin): [sort-ngmodule-metadata-arrays] handle literal metadata and computed properties

packages/eslint-plugin-template/src/rules/i18n.ts, packages/eslint-plugin-template/tests/rules/i18n/cases.ts
Currently, the i18n rule has a suggestion that doesn't do anything. It was introduced in https://github.com/angular-eslint/angular-eslint/commit/25234c80b5bca3700d3ca71ab9181a8dc1ff1360 and it basically acts like a hint telling the user to add some config to the `.eslint` file, but IMHO it's unnecessary. We don't do this for any other option in this or other rule. Why should this be treated differently?
=> refactor(eslint-plugin-template): [i18n] remove non-actionable suggestion

package.json, packages/integration-tests/project.json, packages/integration-tests/tests/__snapshots__/v1123-multi-project-manual-config.test.ts.snap
Found while working on something else.
Current state: If you run integration-tests locally multiple times locally yarn and npm will not be doing a full install on each fixture Angular CLI workspace so you can end up using a stale copy of a package when the linting/assertions run.
I believe the touched snapshot here stayed out of date as a result
=> chore(integration-tests): fix snapshot and ensure clean fixtures pre run

packages/eslint-plugin-template/src/processors.ts, packages/eslint-plugin-template/tests/processors.test.ts
=> fix(eslint-plugin-template): support escape chars in inline templates

packages/eslint-plugin/docs/rules/sort-ngmodule-metadata-arrays.md, packages/eslint-plugin/src/rules/sort-ngmodule-metadata-arrays.ts, packages/eslint-plugin/tests/rules/sort-ngmodule-metadata-arrays/cases.ts
We currently report the node that precedes the violation. With this PR, it should be no longer a problem.
=> fix(eslint-plugin): [sort-ngmodule-metadata-arrays] report the correct node

packages/eslint-plugin/docs/rules/sort-ngmodule-metadata-arrays.md, packages/eslint-plugin/src/rules/sort-ngmodule-metadata-arrays.ts, packages/eslint-plugin/tests/rules/sort-ngmodule-metadata-arrays/cases.ts
Commit 1 is from #693 and that PR should be merged first.
---
We currently have a restriction to search only some properties, but we don't need to. The rule should report all unordered arrays within `NgModule`, whatever the property name is.
=> fix(eslint-plugin): [sort-ngmodule-metadata-arrays] remove the property restriction

.github/workflows/ci.yml, packages/eslint-plugin/docs/rules/no-attribute-decorator.md, packages/eslint-plugin/src/rules/no-attribute-decorator.ts
Closes #237
I spoke with Minko from the Angular Team and agreed on this change in language to make it clearer why the rule exists
=> fix(eslint-plugin): more appropriate language for no-attribute-decorator

packages/eslint-plugin-template/docs/rules/i18n.md, packages/eslint-plugin-template/src/rules/i18n.ts, packages/eslint-plugin-template/tests/rules/i18n/cases.ts
This pull request adds the option to enforce the requirement of a description for i18n metadata. Per the Angular guide, "To translate a text message accurately, provide additional information or context for the translator." This is especially helpful when working in projects that contain large amounts of translatable texts.
P.S.
- If this feature is sound, would it be worth adding the option to require the meaning for i18n metadata? If so, in this PR, or a follow-up? Maybe something like: `"requireMetadata": ["meaning", "description"]`
- The logic for this feature adds a conditional statement with the existing logic for checking the ID. Even though all of the tests are still passing, please provide any feedback on the changes to `handleElement(...)`.
Any/all feedback welcome. 😄
=> feat(i18n): option to require description for i18n metadata

packages/schematics/package.json
`ng update` checks the "ng-update"."packageGroup" field in the package.json for related packages. If defined these will also be updated to the resolved version: https://github.com/angular/angular-cli/blob/master/docs/specifications/update.md#library-developers
This simplifies the update procedure; Consumers will only have to execute `ng update @angular-eslint/schematics`, which will update all installed `@angular-eslint/*` packages.
=> feat: add package group for ng update

packages/eslint-plugin-template/src/utils/create-eslint-rule.ts, packages/eslint-plugin/src/utils/create-eslint-rule.ts
Fixes #889
Also removes the deep imports into typescript-eslint
=> fix: rule docs links in create-eslint-rule utils

packages/eslint-plugin-template/docs/rules/conditional-complexity.md, packages/eslint-plugin-template/project.json, packages/eslint-plugin-template/src/index.ts, packages/eslint-plugin-template/src/rules/conditional-complexity.ts, packages/eslint-plugin-template/tests/rules/conditional-complexity/cases.ts, packages/eslint-plugin/project.json
=> fix(eslint-plugin-template): false positive conditional complexity in BoundAttribute > Interpolation

packages/eslint-plugin-template/src/rules/eqeqeq.ts
Fix an issue where the suggest message for the `eqeqeq` rule suggests that you replace the "expected" value with the "actual" value instead of the other way around.
=> fix(eslint-plugin-template): [eqeqeq] update suggest message

packages/eslint-plugin/docs/rules/sort-ngmodule-metadata-arrays.md, packages/eslint-plugin/src/rules/sort-ngmodule-metadata-arrays.ts, packages/eslint-plugin/tests/rules/sort-ngmodule-metadata-arrays/cases.ts
The rule currently sorts the `deps` property of factory providers which scrambles the order the arguments are given to the function.
New behavior: `deps` property is excluded from selector.
Closes #703
=> fix(eslint-plugin): [sort-ngmodule-metadata-arrays] do not sort deps property

README.md
1. `.prettierc` can't contain comments
2. the `parser` option should be in the `options` option https://prettier.io/docs/en/configuration.html#setting-the-parserdocsenoptionshtmlparser-option
Fixes #1144.
=> docs: fix .prettierrc in eslint-plugin-prettier section

packages/eslint-plugin-template/docs/rules/accessibility-elements-content.md, packages/eslint-plugin-template/src/rules/accessibility-elements-content.ts, packages/eslint-plugin-template/tests/rules/accessibility-elements-content/cases.ts
Resolves #1169 
Adds allowList option to the accessibility-elements-content rule to configure additional attributes, inputs, or attribute directives that satisfy the content criteria.
=> feat(eslint-plugin-template): [accessibility-elements-content] add allowList option

packages/eslint-plugin-template/docs/rules/no-call-expression.md, packages/eslint-plugin-template/src/rules/no-call-expression.ts, packages/eslint-plugin-template/tests/rules/no-call-expression/cases.ts
Resolves #1055
Adds `allowList` option to the no-call-expression template rule to configure a list of function names allowed to be called.
=> feat(eslint-plugin-template): [no-call-expression] add allowList option

packages/eslint-plugin-template/docs/rules/accessibility-valid-aria.md, packages/eslint-plugin-template/src/rules/accessibility-valid-aria.ts, packages/eslint-plugin-template/tests/rules/accessibility-valid-aria/cases.ts
Fixes parsing plain text numeric attribute values: accessibility-valid-aria is currently just allowing for bound numeric attribute values but not parsing from plain text values, e.g. `aria-valuemin="1"`
=> fix(eslint-plugin-template): [accessibility-valid-aria] use Number() to parse numeric values

packages/eslint-plugin-template/docs/rules/no-negated-async.md, packages/eslint-plugin-template/src/rules/no-negated-async.ts, tools/scripts/generate-rule-docs.ts
It's a real strength that we generate our rule documentation from both the rule implementations and unit tests. However, ESLint has a limited concept of rule documentation within the rule implementation itself - only a concise description is intended to be stored there.
Therefore, this PR introduces a simple `RULE_DOCS_EXTENSION` which a rule implementation file can optionally export and which will be used to generated a more extended rule rationale
Closes #1226
=> chore: add optional RULE_DOCS_EXTENSION export for extended rule rationale

packages/eslint-plugin/docs/rules/no-input-rename.md, packages/eslint-plugin/src/rules/no-input-rename.ts, packages/eslint-plugin/tests/rules/no-input-rename/cases.ts
=> fix(eslint-plugin): [no-input-rename] do not report on directive composition API

packages/eslint-plugin-template/docs/rules/i18n.md, packages/eslint-plugin-template/src/rules/i18n.ts, packages/eslint-plugin-template/tests/rules/i18n/cases.ts
This pull request adds the option to `requireMeaning` when adding i18n metadata in templates.
=> feat(eslint-plugin-template): [i18n] option to require i18n meaning

.github/workflows/update-integration-tests-for-renovate.yml, packages/integration-tests/tests/__snapshots__/v13-new-workspace-create-application-false-ng-add-then-project.test.ts.snap, packages/integration-tests/tests/__snapshots__/v13-new-workspace-create-application-false-project-then-ng-add.test.ts.snap, packages/integration-tests/tests/__snapshots__/v13-new-workspace.test.ts.snap, packages/integration-tests/tests/v13-new-workspace-create-application-false-ng-add-then-project.test.ts, packages/integration-tests/tests/v13-new-workspace-create-application-false-project-then-ng-add.test.ts, packages/integration-tests/tests/v13-new-workspace.test.ts, packages/integration-tests/utils/snapshot-serializers.ts
There is a frustrating amount of friction in some integration test snapshots currently because of minor or patch version bumps happening via the Angular CLI tooling. We do not control these so there is no great value in tracking them granularly within snapshots.
This PR adds custom serialization logic to normalize the relevant minor and patch versions (we still want to catch and deal with any major version changes)
=> chore: normalize pkg versions we do not control in snapshots

packages/utils/src/rules-tester.ts
Currently, when `options.parserOptions.project` is specified, we set the filename to be `path.join(process.cwd(), 'tests/fixtures/')`. This can be problematic when we run the test from a higher-up parent directory as it will use that as the base directory and look for `'tests/fixtures/file.ts` from there.
Instead, we should use `options.parserOptions.tsconfigRootDir` as the base directory when specified and resolve `file.ts` from there. This is similar to how `@typescript-eslint` does it: https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/utils/src/eslint-utils/rule-tester/RuleTester.ts#L122-L137
=> fix(utils): use tsconfigRootDir as root dir when specified

packages/utils/src/rules-tester.ts
Addresses #898
- For valid and invalid test cases, use the test case's filename if specified, otherwise, use `this.filename`
=> fix(utils): use test case filename when specified

packages/eslint-plugin/src/configs/all.json, packages/eslint-plugin/src/index.ts
Prevents the `Definition for rule '@angular-eslint/require-localize-metadata' was not found` ESLint error.
Also, fix sorted order for the `prefer-standalone-component` rule.
=> fix(eslint-plugin): export require-localize-metadata rule

packages/eslint-plugin-template/src/rules/i18n.ts
In the i18n rule messages some links to the Angular i18n docs are used, however some of them are broken since Angular 12 due to a i18n docs refactor. This PR updates those links to their right location in the current version of the Angular i18n docs.
Closes #1475
=> fix(eslint-plugin-template): update links to Angular i18n docs

package.json, yarn.lock
Reverts angular-eslint/angular-eslint#1498
Even though this was green, need to stay in sync with https://angular.io/guide/versions
=> Revert "chore: update dependency typescript to v5.2.2"

packages/eslint-plugin-template/src/processors.ts, packages/eslint-plugin-template/tests/processors.test.ts, packages/integration-tests/suites/4/project.json, packages/integration-tests/tests/__snapshots__/inline-template-fixer.test.ts.snap, packages/integration-tests/tests/inline-template-fixer.test.ts, packages/integration-tests/utils/run-lint.ts
Currently, the rule fixer does not return correct results for inline templates. It applies to all template rules with a fixer, see https://github.com/angular-eslint/angular-eslint/issues/1464#issuecomment-1673008115. This is fixed by this PR.
Closes #1464 
Note: I wanted to add some tests, but I'm not sure where to start. I performed manual tests of all the cases described in the linked issue.
=> fix(eslint-plugin-template): fix fixer of inline templates

packages/eslint-plugin-template/docs/rules/prefer-self-closing-tags.md, packages/eslint-plugin-template/src/rules/prefer-self-closing-tags.ts, packages/eslint-plugin-template/tests/rules/prefer-self-closing-tags/cases.ts
Currently when running the fixer of the `prefer-self-closing-tags` rule, in some scenarios a result is generated, which is considered as bad code style by common sense and formatters like prettier. More specifically, currently the fixer always adds an additional whitespace before the self closing tag. However when the end of the starting tag is indented or on a new line, this additional whitespace produces misalignment.
For example, take the following code:
```html
<my-component
someAttribute="someValue"
></my-component>
```
Currently the fixer would produce the following reusult:
```html
<my-component
someAttribute="someValue"
/>
```
With the changes of this PR it would become:
```html
<my-component
someAttribute="someValue"
/>
```
=> fix(eslint-plugin-template): [prefer-self-closing-tags] improve code style of fixer result

packages/eslint-plugin-template/docs/rules/use-track-by-function.md, packages/eslint-plugin-template/jest.config.ts, packages/eslint-plugin-template/src/rules/use-track-by-function.ts, packages/eslint-plugin-template/tests/rules/use-track-by-function/cases.ts
This commit adds an `alias` option to the `use-track-by-function` rule, allowing the specification of a list of properties that should be treated similarly to `ngForTrackBy`.
Closes #1323
=> feat(eslint-plugin-template): allow `alias` option in [use-track-by-function]

packages/nx-plugin/src/generators/rule/files/src/rules/__ruleName__.ts.template
This pull request fixes the template for the new rule generator by removing `defaultOptions` from the `meta` object, as the property does not belong there.
=> chore: fix rule generator template defaultOptions

packages/eslint-plugin-template/docs/rules/prefer-self-closing-tags.md, packages/eslint-plugin-template/src/rules/prefer-self-closing-tags.ts, packages/eslint-plugin-template/tests/rules/prefer-self-closing-tags/cases.ts, yarn.lock
Currently the prefer-self-closing-tags rule doesn't report errors on  empty `<ng-content></ng-content>` and `<ng-template></ng-template>` elements, which is fixed by this pull request.
Closes #1567
=> fix(eslint-plugin-template): [prefer-self-closing-tags] consider ng-content and ng-template elements

packages/eslint-plugin-template/tsconfig.build.json, packages/eslint-plugin/tsconfig.build.json, packages/schematics/tsconfig.build.json, packages/template-parser/tsconfig.build.json
Some of the `@angular-eslint/*` packages declare a `"types"` field in their published `package.json`, however their respective `tsconfig.build.json` configuration files lack the`"declaration": true` field.
This means that no `.d.ts` files will be created for these packages when building the package for publishing to npm, causing the `"types"` field to reference a missing file.
This PR fixes this, allowing the published npm packages to be imported directly within a TypeScript project.
=> fix: generate type declarations for published packages

packages/eslint-plugin-template/docs/rules/prefer-ngsrc.md, packages/eslint-plugin-template/src/rules/prefer-ngsrc.ts, packages/eslint-plugin-template/tests/rules/prefer-ngsrc/cases.ts
Closes https://github.com/angular-eslint/angular-eslint/issues/1543
Rule prefer-ngsrc should not error if image src is a base64-encoded string because NgOptimizedImage does not support Base64-encoded strings.
Expected Behavior:
`<img src="data:image/png;base64" />` ✅ should not throw an error
`<img [src]="'data:image/png;base64'" /> ` ❌ should throw an error because `[src]` is a BoundAttribute
`<img src="data:image/png;base64" [ngSrc]="'data:image/png;base64'" />` ❌ should throw an error because there is two sources.
=> fix(eslint-plugin-template): [prefer-ngsrc] Do not prefer ngsrc for base64-encoded strings

packages/eslint-plugin/docs/rules/component-max-inline-declarations.md, packages/eslint-plugin/src/rules/component-max-inline-declarations.ts, packages/eslint-plugin/tests/rules/component-max-inline-declarations/cases.ts
This fix is for `component-max-inline-declarations` rule to also apply for `styles` with a `string`:
```ts
@Component({
styles: `
:host { display: block; }
`
})
class Foo {}
```
=> fix(eslint-plugin): fix max inline declarations rule for styles string

packages/eslint-plugin-template/docs/rules/i18n.md, packages/eslint-plugin-template/src/rules/i18n.ts, packages/eslint-plugin-template/tests/rules/i18n/cases.ts
Fixes a regression caused by https://github.com/angular-eslint/angular-eslint/pull/1257 where i18n attributes on structural directives are not propertly detected. The fix is to tighten the `isTemplate` helper to only check for `ng-template` nodes and not all template nodes which are created by using a structural directive.
First commit is from https://github.com/angular-eslint/angular-eslint/pull/1656 which this PR builds on as it requires the fix from that PR as well.
=> fix(eslint-plugin-template): handle i18n tags on structural direcives

tsconfig.base.json
=> fix: output declaration files in all packages

packages/eslint-plugin/README.md, packages/eslint-plugin/docs/rules/sort-ngmodule-metadata-arrays.md, packages/eslint-plugin/src/rules/sort-ngmodule-metadata-arrays.ts, tools/scripts/generate-rule-docs.ts
This pull request deprecates rule `sort-ngmodule-metadata-arrays`; see discussions in #1232.
Because there is no replacement for this rule, this pull request also updates the rule doc generator to not include a rule replacement note if one is not available.
Closes #1232
=> chore(eslint-plugin): [sort-ngmodule-metadata-arrays] deprecate rule

.github/workflows/ci.yml, .github/workflows/publish.yml
Skip publish workflow on forked repositories
Publish workflow is executed on forks:
https://github.com/chimurai/angular-eslint/actions/runs/9324614358
=> ci(github-action): skip publish on forks

packages/test-utils/src/rule-tester.ts
The `RuleTester` class from `@typescript-eslint/rule-tester` can be extended for various testing frameworks by updating `RuleTester.describe`, `RuleTester.afterAll`, etc. But the Angular one is hard-coded to a `globalThis.afterAll`, and ignores `RuleTester.afterAll`. This PR will make `@angular-eslint/test-utils` respect `RuleTester.afterAll`, by using that first if it exists.
=> fix(test-utils): use configured RuleTester.afterAll over global

packages/eslint-plugin-template/docs/rules/prefer-self-closing-tags.md, packages/eslint-plugin-template/src/rules/prefer-self-closing-tags.ts, packages/eslint-plugin-template/tests/rules/prefer-self-closing-tags/cases.ts
Since Angular 18, `<ng-content>` can be used with a fallback content. The `prefer-self-closing-tags` rule currently raises an error when using this feature, see https://github.com/angular-eslint/angular-eslint/issues/1567#issuecomment-2156430905.
=> fix(eslint-plugin-template): [prefer-self-closing-tags] support ng-content with fallback content

packages/eslint-plugin/docs/rules/prefer-standalone.md, packages/eslint-plugin/src/rules/prefer-standalone.ts, packages/eslint-plugin/tests/rules/prefer-standalone/cases.ts
Do not report `@Decorator()` as not standalone. Empty decorator is needed on base classes of directives and components if the base class uses Angular features.
Similar exception already exists on e.g. directive-class-suffix (#394)
Closes #1910
=> fix(eslint-plugin): [prefer-standalone] ignore empty Directive decorators

packages/eslint-plugin-template/docs/rules/interactive-supports-focus.md, packages/eslint-plugin-template/src/rules/interactive-supports-focus.ts, packages/eslint-plugin-template/tests/rules/interactive-supports-focus/cases.ts
Resolves #1429 
Adds an `allowList` to the interactive-supports-focus template rule to with `<form>` as a default option to allow for event bubbling and capturing events from `<form>` elements. 
* The `allowList` can be configured as an empty array to more strictly permit click and key events on interactive elements only
* Additional HTML or custom elements can be configured and added to the `allowList` array to permit click and key events on elements that are otherwise not interactive
=> fix(eslint-plugin-template): [interactive-supports-focus] allowList with form as default option to support event bubbling

packages/eslint-plugin-template/docs/rules/prefer-self-closing-tags.md, packages/eslint-plugin-template/src/rules/prefer-self-closing-tags.ts, packages/eslint-plugin-template/tests/rules/prefer-self-closing-tags/cases.ts
Currently if the `prefer-self-closing-tags` rule is used, and the template contains an `<ng-content>` with default content containing HTML markup, a false positive error is reported.
Closes #1970
=> fix(eslint-plugin-template): [prefer-self-closing-tags] fix ng-content with rich default content

packages/eslint-plugin-template/src/rules/prefer-self-closing-tags.ts
Updated the condition to check for both `src/index.html` and `src\index.html` paths in order to support Windows file paths.
=> fix(prefer-self-closing-tags): handle both forward and backward slash

packages/eslint-plugin-template/docs/rules/no-call-expression.md, packages/eslint-plugin-template/tests/rules/no-call-expression/cases.ts, packages/template-parser/src/index.ts, packages/template-parser/tests/index.test.ts, packages/test-utils/src/convert-annotated-source-to-failure-case.ts
When traversing a Call AST node, ESLint would never visit its receiver/callee. Since Call didn't have visitor keys listed explicitly, the parser would use `getFallbackKeys`, which seems to be buggy as it only returns `args` and not `receiver`.
Update test cases for no-call-expression to deal with new call expressions being reported.
Since convertAnnotatedSourceToFailureCase doesn't deal well with overlapping errors at the moment, instances of `()()` were removed from existing tests and added as separate cases for nested calls.
Closes #1885
=> fix(template-parser): visit receiver of Call expression

.npmrc, .prettierignore, nx.json, packages/angular-eslint/package.json, packages/eslint-plugin-template/package.json, packages/eslint-plugin/package.json, packages/schematics/package.json, packages/template-parser/package.json, packages/test-utils/package.json, packages/utils/package.json, pnpm-lock.yaml
As of `19.7.2`, `nx release` now supports leaving workspace dependency protocols in place while preserving all other versioning logic and then delegating to `pnpm publish` at publish time which supports swapping these references out for the appropriate semver numbers.
(NOTE: `npm publish` does not support this, so it's only applicable for pnpm users, which angular-eslint is, so we can make this change)
=> chore: use workspace protocol for local dependencies

packages/eslint-plugin/docs/rules/prefer-standalone.md, packages/eslint-plugin/src/rules/prefer-standalone.ts, packages/eslint-plugin/tests/rules/prefer-standalone/cases.ts
In Angular 19, [standalone will be the new default](https://blog.angular.dev/the-future-is-standalone-475d7edbc706). There will also be an automigration which removes the `standalone: true` property from the metadata. This plugin needs to be updated in order to adapt to those changes.
Note: It would be better if the fixer would remove the whole attribute, but with the given tooling this is not so easy to achieve. For now the fixer will transform the `standalone: false` attribute to `standalone: true`.
=> feat(eslint-plugin)!: prefer-standalone recognizes that standalone is the default

packages/eslint-plugin-template/docs/rules/prefer-self-closing-tags.md, packages/eslint-plugin-template/src/rules/prefer-self-closing-tags.ts, packages/eslint-plugin-template/tests/rules/prefer-self-closing-tags/cases.ts
Fixes #1700
Fixes #1715
The bug was caused by the fact that the template parser decodes HTML entities. For example if the text content of a node is "&nbsp;", then that is parsed to a `TmplAstText` object with a value of " ". Likewise, `&#9;` is parsed to "\t", and so on.
So rather than checking if the `TmplAstText.value` property is whitespace, we need to get the corresponding text from the _source code_ and see if that text is whitespace.
=> fix(eslint-plugin-template): [prefer-self-closing-tags] do not remove HTML-encoded whitespace

packages/eslint-plugin/docs/rules/prefer-signals.md, packages/eslint-plugin/src/rules/prefer-signals.ts, packages/eslint-plugin/tests/rules/prefer-signals/cases.ts
=> feat(eslint-plugin): prefer-signals now checks .asReadonly() calls

packages/eslint-plugin-template/docs/rules/attributes-order.md, packages/eslint-plugin-template/src/rules/attributes-order.ts, packages/eslint-plugin-template/tests/rules/attributes-order/cases.ts
Fixes #2192 
When an `ng-template` is within an `svg` element, its tag name is `:svg:ng-template`.
=> fix(eslint-plugin-template): [attribute-order] check for ng-template within svg

packages/eslint-plugin-template/docs/rules/attributes-order.md, packages/eslint-plugin-template/docs/rules/eqeqeq.md, packages/eslint-plugin-template/docs/rules/label-has-associated-control.md, packages/eslint-plugin-template/docs/rules/no-call-expression.md, packages/eslint-plugin-template/docs/rules/no-duplicate-attributes.md, packages/eslint-plugin-template/docs/rules/no-inline-styles.md, packages/eslint-plugin/docs/rules/component-selector.md, packages/eslint-plugin/docs/rules/directive-selector.md, packages/eslint-plugin/docs/rules/prefer-signals.md, packages/eslint-plugin/docs/rules/require-localize-metadata.md, tools/scripts/generate-rule-docs.ts
Fixes #1749 
Options that had a default value of `false`, `0`, `""`, `null` or `undefined` would not show their default value in the docs.
=> docs: show falsy default values

packages/eslint-plugin-template/docs/rules/prefer-self-closing-tags.md, packages/eslint-plugin-template/src/rules/prefer-self-closing-tags.ts, packages/eslint-plugin-template/tests/rules/prefer-self-closing-tags/cases.ts
Fixes #2060 
The immediate fix was actually quite simple - anchor the regular expression at the start and end of the string. The problem was that when there were nested `ng-content` nodes, the regular expression might not match to the first `<ng-content` tag and/or not match to the last `</ng-content>` tag. In the example from #2060:
```html
<ng-content select="[slot='icon-only']">
<ng-content select="[slot=start]" />
<ng-content />
<ng-content select="[slot=end]" />
</ng-content>
```
The regular expression matches to:
```
<ng-content select="[slot=end]" />
</ng-content>
```
Adding `^` and `$` anchors to the regular expression would fix that, but the problem with using a regular expression is that it doesn't handle quotes. If a selector contained a ">" then it would incorrectly find the …
=> fix(eslint-plugin-template): [prefer-self-closing-tags] allow nested ng-content

packages/eslint-plugin-template/docs/rules/prefer-static-string-properties.md, packages/eslint-plugin-template/src/rules/prefer-static-string-properties.ts, packages/eslint-plugin-template/tests/rules/prefer-static-string-properties/cases.ts
Fixes #2237 
A simple fix. The rule should only check `BoundAttribute` nodes that are in the `inputs` collection of an element, and not in the `templateAttrs` collection.
=> fix(eslint-plugin-template): [prefer-static-string-properties] do not check structural directives

packages/angular-eslint/tsconfig.spec.json, packages/builder/tsconfig.spec.json, packages/eslint-plugin-template/src/processors.ts, packages/eslint-plugin-template/tests/processors.spec.ts, packages/eslint-plugin-template/tsconfig.spec.json, packages/eslint-plugin/tsconfig.spec.json, packages/nx-plugin/tsconfig.spec.json, packages/schematics/tsconfig.spec.json, packages/template-parser/tsconfig.spec.json, packages/test-utils/tsconfig.spec.json, packages/utils/tsconfig.spec.json
Fixes #1825 
Rather than only looking at the statements in a source file to find the class declarations, the preprocessor now walks down the syntax tree to find the class declarations.
This might seem like it will add a bit more work to the processor, but I don't think it will have much of an impact on performance. 
For a typical component file that contains some `import` statements and a class declaration, nothing will change - the syntax tree walking explicitly avoids stepping down into `ImportDeclaration` nodes, and it doesn't step into `ClassDeclaration` nodes, so the net result would be no change to performance.
For a file that contains some more things like type exports, top-level variable assignments and enum declarations, _most_ of those things are also skipped. Variable …
=> fix(eslint-plugin-template): find inline templates on components in blocks

packages/eslint-plugin-template/docs/rules/prefer-static-string-properties.md, packages/eslint-plugin-template/src/rules/prefer-static-string-properties.ts, packages/eslint-plugin-template/tests/rules/prefer-static-string-properties/cases.ts
We don't want to use this rule for directives like `*ngSwitchCase` or `*ngIf`
fixes https://github.com/angular-eslint/angular-eslint/issues/2265
=> fix(prefer-static-string-properties): resolve bug with directives

packages/eslint-plugin-template/docs/rules/prefer-static-string-properties.md, packages/eslint-plugin-template/src/rules/prefer-static-string-properties.ts, packages/eslint-plugin-template/tests/rules/prefer-static-string-properties/cases.ts
Exclude some attributes : 
```
<my-component *ngSwitchCase="'foo'" />
```
```
<my-component [style.color]="'foo'" />
```
```
<my-component [attr.aria-label]="'foo'" />
```
```
<my-component [@fade]="'foo'" />
```
```
<my-component [class.foo]="'foo'" />
```
fixes: #2265
=> fix(prefer-static-string-properties): exclude special attributes

packages/eslint-plugin-template/docs/rules/prefer-self-closing-tags.md, packages/eslint-plugin-template/src/rules/prefer-self-closing-tags.ts, packages/eslint-plugin-template/tests/rules/prefer-self-closing-tags/cases.ts
Fixes #2280
Regression from https://github.com/angular-eslint/angular-eslint/pull/2256
=> fix(eslint-plugin-template): [prefer-self-closing-tags] resolve wrong reports when structural directive + no content + no self-closing

packages/builder/src/lint.impl.spec.ts
Some of the `builder` tests failed on Windows because the tests were checking if the path given to `existsSync` ended with `"/eslint.config.js"`, but the path is `"some\path\to\eslint.config.js"` on Windows.
=> chore(builder): make tests cross-platform

packages/eslint-plugin-template/docs/rules/button-has-type.md, packages/eslint-plugin-template/src/rules/button-has-type.ts, packages/eslint-plugin-template/tests/rules/button-has-type/cases.ts
Fixes #2193 
Adds an `ignoreWithDirectives` option that specifies the names of directives (or attributes) that, when present on the `button` element, will cause the `button-has-type` rule to _not_ report a problem.
I went with "ignore" rather than "allow", but I'm happy to change it to something else if needed.
I've still kept the "invalidType" check, so even if the "missingType" check is skipped, if you specify a `type` attribute with an invalid value, the rule will still report a problem.
=> feat(eslint-plugin-template): [button-has-type] add option to ignore missing type

packages/eslint-plugin-template/docs/rules/attributes-order.md, packages/eslint-plugin-template/src/rules/attributes-order.ts, packages/eslint-plugin-template/tests/rules/attributes-order/cases.ts
Fixes #1519 
i18n attributes are not exposed in the template AST. Instead, the element or attribute that the i18n attribute is associated with has an `i18n` property that stores an `I18nMeta` object, but that object does not define the span of the attribute, so it cannot be used to determine whether the attribute is in the correct order.
This PR changes how attributes are sourced when there is i18n data. If the element or any attribute or input has i18n metadata, then instead of getting the attributes from the template AST, Angular's `HtmlParser` is used to parse the element to get the raw attributes before they were manipulated into the template AST.
This technique is only used when i18n metadata exists to avoid re-parsing the attributes when they are all present in the template AST. …
=> fix(eslint-plugin-template): [attributes-order] order i18n attributes

packages/eslint-plugin-template/docs/rules/attributes-order.md, packages/eslint-plugin-template/src/rules/attributes-order.ts, packages/eslint-plugin-template/tests/rules/attributes-order/cases.ts
Fixes #1914 
Given an element with two attributes, where one sets a static valid and the other uses interpolation, Angular classifies the first attribute as an "attribute" and the second attribute as an "input". 
```html
<div a="b" c="{{ d }}"></div>
```
See here for an example of the AST (the template parser it uses is quite a few versions behind, but the same behavior exists with v19):
https://astexplorer.net/#/gist/cd84edb20d811a8896c9f28f6f5031d9/1567654ea0ba120f0c3844e9786387bb3c921d17
This pull request changes the `attributes-order` rule such that an input will only be classified as an input if it's surrounded with square brackets.
> [!NOTE]
> ~~This PR is piggy-backing off #2307 since that PR made large changes to the `attributes-order` rule. Once/if that is merged, then I'll …
=> fix(eslint-plugin-template): [attributes-order] treat inputs without square brackets as attributes

packages/eslint-plugin-template/src/processors.ts, packages/eslint-plugin-template/tests/processors.spec.ts
Fixes #2356 
The problem was that the `column` and `endColumn` were not being adjusted when transforming the message locations from being within the inline template string to being within the full code file that the inline template was in. Not adjusting the columns is the correct thing to do for anything _but_ the first line, because the second and subsequent lines always start at column 1, while the first line starts wherever the string starts on that line, plus one character for the opening quote.
=> fix(eslint-plugin-template): correct column adjustment for inline template message locations

packages/eslint-plugin-template/docs/rules/prefer-template-literal.md, packages/eslint-plugin-template/src/rules/prefer-template-literal.ts, packages/eslint-plugin-template/tests/rules/prefer-template-literal/cases.ts
In some cases (when autofix result is a template), a parenthesis is removed but not both.
`'prefix-' + (condition ? 'true' : 'false')` => `` `prefix-${condition ? 'true' : 'false'}`)``
`('value' | pipe) + "-suffix"` => ``(`${'value' | pipe}-suffix` ``
If node is surronded by parentheses remove them, with template literal they become useless
=> fix(eslint-plugin-template): [prefer-template-literal] handle parentheses in autofix

AGENTS.md
- add AGENTS.md describing Codex usage guidelines
- `pnpm lint-staged` (run via pre-commit hook)
=> docs: introduce AGENTS guidelines

packages/builder/src/utils/eslint-utils.ts
- fix the option name typo in builder's flat config error message
- `NX_NO_CLOUD=true pnpm nx lint builder --skip-nx-cache`
- `NX_NO_CLOUD=true pnpm nx test builder --skip-nx-cache`
=> fix(builder): correct option name in flat config error

docs/CONFIGURING_FLAT_CONFIG.md
- fix code sample in `CONFIGURING_FLAT_CONFIG.md`
- `pnpm format-check`
- `pnpm nx sync:check`
- `NX_NO_CLOUD=true pnpm nx run-many -t check-rule-docs`
- `NX_NO_CLOUD=true pnpm nx run-many -t check-rule-lists`
- `NX_NO_CLOUD=true pnpm nx run-many -t check-rule-configs`
=> docs: correct prettier configuration example

packages/template-parser/src/index.ts
- update `template-parser` imports for eslint-scope@8 typings
- construct ScopeManager and Scope via the new class names
- `pnpm format-check`
- `timeout 60s bash -c 'NX_NO_CLOUD=true pnpm nx run template-parser:build --output-style=stream'`
=> chore(template-parser): adapt to new eslint-scope types

packages/eslint-plugin-template/docs/rules/eqeqeq.md, packages/eslint-plugin-template/docs/rules/no-call-expression.md, packages/eslint-plugin-template/docs/rules/prefer-ngsrc.md, packages/eslint-plugin-template/tests/rules/eqeqeq/cases.ts, packages/eslint-plugin-template/tests/rules/i18n/cases.ts, packages/eslint-plugin-template/tests/rules/no-call-expression/cases.ts, packages/eslint-plugin-template/tests/rules/prefer-ngsrc/cases.ts, packages/template-parser/src/index.ts, packages/template-parser/tests/index.test.ts, packages/test-utils/src/convert-annotated-source-to-failure-case.ts
Fixes #1641
🚨 Breaking change 🚨
Template parse errors will now result in an error from ESLint.
~~Note: This is currently blocked by #2256.~~
=> feat(template-parser)!: do not suppress parse errors by default

packages/schematics/README.md, packages/schematics/src/ng-add/index.ts, packages/schematics/src/ng-add/schema.json, packages/schematics/src/ng-add/schema.ts
- add skipInstall schema option for `ng-add`
- document new flag and usage example
- allow `--skip-install` to skip NodePackageInstallTask
- log install instructions when skipping dependencies
- `pnpm jest packages/schematics --runInBand`
- `pnpm format-check`
- `pnpm nx sync:check`
- `NX_NO_CLOUD=true pnpm nx run-many -t check-rule-docs --parallel=1`
- `NX_NO_CLOUD=true pnpm nx run-many -t check-rule-lists --parallel=1`
- `NX_NO_CLOUD=true pnpm nx run-many -t check-rule-configs --parallel=1`
=> feat(schematics): support --skip-install for ng-add

packages/builder/README.md, packages/builder/src/lint.impl.spec.ts, packages/builder/src/schema.d.ts, packages/builder/src/schema.json, packages/builder/src/utils/eslint-utils.spec.ts, packages/builder/src/utils/eslint-utils.ts
- expose `--stats` option in the lint builder schema
- support `stats` in builder implementation and util
- document the stats option
- test stats option and stats output
Fixes #1370
=> feat(builder): add stats option

packages/schematics/src/ng-add/index.ts, packages/schematics/tests/ng-add/index.test.ts
=> fix(schematics): ensure @eslint/js and @angular-eslint/builder are always available in non-npm repos

packages/eslint-plugin-template/docs/rules/label-has-associated-control.md, packages/eslint-plugin-template/src/rules/label-has-associated-control.ts, packages/eslint-plugin-template/tests/rules/label-has-associated-control/cases.ts
=> fix(eslint-plugin-template): [label-has-associated-control] labelComponents should override default label inputs

packages/eslint-plugin/docs/rules/no-developer-preview.md, packages/eslint-plugin/docs/rules/no-experimental.md, packages/eslint-plugin/src/rules/no-developer-preview.ts, packages/eslint-plugin/src/rules/no-experimental.ts
Add reasoning for the new `no-experimental` and `no-developer-preview` rules, see #1447
=> docs(eslint-plugin): add rationale for no-experimental and no-developer-preview

packages/eslint-plugin-template/docs/rules/no-interpolation-in-attributes.md, packages/eslint-plugin-template/src/rules/no-interpolation-in-attributes.ts, packages/eslint-plugin-template/tests/rules/no-interpolation-in-attributes/cases.ts
Fix for released version 19.8: https://github.com/angular-eslint/angular-eslint/pull/2501
This PR fixes an issue in the no-interpolation-in-attributes rule where attributes using attr. (e.g. `attr.data-*`) were incorrectly autofixed by removing the attr. prefix. The fixer now correctly preserves the full attribute name, ensuring proper binding syntax like `[attr.data-example]="..."`.
If this fix is valid, I'd appreciate it if it could still be included in a v19 release, if possible.
=> fix(eslint-plugin-template): [no-interpolation-in-attributes] use keySpan as attr. range and sourceSpan as replacement range

packages/eslint-plugin/docs/rules/relative-url-prefix.md, packages/eslint-plugin/src/rules/relative-url-prefix.ts, packages/eslint-plugin/tests/rules/relative-url-prefix/cases.ts
=> fix(eslint-plugin): [relative-url-prefix] handle template literals
