.gitignore
This PR excludes JetBrain configuration from git.
=> chore: exclude `.idea` folder from git

packages/eslint-plugin/src/index.ts
=> fix(eslint-plugin): add component-selector into index.ts

packages/builder/src/index.ts, packages/builder/src/schema.json
Allow the --cache option to be passed to the eslint cli engine.
Needed for: https://github.com/nrwl/nx/issues/2337
=> feat: 🎸 add caching (allow eslint --cache)

packages/eslint-plugin/src/index.ts, packages/eslint-plugin/src/rules/prefer-output-readonly.ts
=> fix(eslint-plugin): prefer-output-readonly rule name

packages/eslint-plugin-template/src/index.ts
Fixes #45 , https://github.com/angular-eslint/angular-eslint/commit/a7fc74ad01c0796adb2456e7c49532e7536b0f2b#commitcomment-37537377
=> fix(eslint-plugin-template): missing rule export "no-negated-async" 

packages/builder/package.json, packages/eslint-plugin-template/package.json, packages/eslint-plugin/package.json, packages/template-parser/package.json
=> docs(*): add repository link to each package.json

README.md, packages/eslint-plugin/src/index.ts, packages/eslint-plugin/src/rules/pipe-prefix.ts, packages/eslint-plugin/src/utils/utils.ts, packages/eslint-plugin/tests/rules/pipe-prefix.test.ts
Implement pipe prefix rule behavior of codelyzer.
=> feat(eslint-plugin): pipe-prefix rule

README.md
=> docs(readme): Usage without Angular CLI Builder

packages/schematics/src/add-config-to-project/files/root-files/.eslintrc.json__tmpl__, packages/schematics/tests/add-config-to-project/index.test.ts
Create valid JSON .eslintrc.json file for #138
=> fix(schematics): create valid .eslintrc.json

README.md
=> chore: update VSCode settings.json docs

packages/eslint-plugin-template/src/processors.ts, packages/eslint-plugin-template/tests/processors.test.ts
Resolve https://github.com/angular-eslint/angular-eslint/issues/151
=> fix(eslint-plugin-template): handle optional fix prop in postprocessor, fixed preprocessor return type

packages/eslint-plugin-template/src/processors.ts, packages/eslint-plugin-template/tests/processors.test.ts
=> fix(eslint-plugin-template): regression in processor

packages/builder/src/index.ts, packages/builder/tests/index.test.ts
=> fix(builder): check for quiet flag when logging results

packages/eslint-plugin/src/configs/recommended.json, packages/integration-tests/fixtures/angular-cli-workspace/.eslintrc.json
Changes to recommended config will be classed as a breaking change post v1 and to help make things clearer before that, will be bumping the the prerelease number to 0.6
=> feat(eslint-plugin): allowTemplateLiterals for quotes in recommended

packages/eslint-plugin/src/utils/property-selector.ts, packages/eslint-plugin/src/utils/utils.ts, packages/eslint-plugin/tests/rules/component-selector.test.ts, packages/eslint-plugin/tests/rules/directive-selector.test.ts
=> fix(eslint-plugin): directive-selector does not ignore indentation differences nor work with multiple selectors

README.md, packages/eslint-plugin-template/src/index.ts, packages/eslint-plugin-template/src/rules/use-track-by-function.ts, packages/eslint-plugin-template/tests/rules/use-track-by-function.test.ts
I implemented ESLint rule corresponding to http://codelyzer.com/rules/template-use-track-by-function/
=> feat(eslint-plugin-template): use-track-by-functions

README.md, packages/eslint-plugin-template/src/configs/all.json, packages/eslint-plugin-template/src/index.ts, packages/eslint-plugin-template/src/rules/i18n.ts, packages/eslint-plugin-template/tests/rules/i18n.test.ts
Hi,
I just recycled the this pull request: https://github.com/angular-eslint/angular-eslint/pull/96 and added unit tests and ignoreTags Option.
Best,
Timo
=> feat(eslint-plugin-template): template-i18n rule with ignoreTags option

packages/eslint-plugin/src/rules/relative-url-prefix.ts, packages/eslint-plugin/tests/rules/relative-url-prefix.test.ts
=> feat(eslint-plugin): support ../ in relative-url-prefix

README.md
=> docs: add full explanation of debug command

packages/eslint-plugin/docs/rules/component-selector.md
Created documentation for rule [component-selector](https://github.com/angular-eslint/angular-eslint/blob/master/packages/eslint-plugin/src/rules/component-selector.ts) in accordance to the documentation effort #197.
=> docs: created docs for rule 'component-selector'

README.md, tools/utils/generate-rules-list.ts
=> docs: add prefer-inline-decorator to wontFix

.github/workflows/ci.yml, .github/workflows/next-major-release.yml, packages/builder/src/index.ts, packages/builder/tests/index.test.ts, packages/integration-tests/tests/__snapshots__/v1014-multi-project-manual-config.test.ts.snap
=> fix(builder): pass all results to a single call to format

README.md
Closes: https://github.com/angular-eslint/angular-eslint/issues/105
=> docs: add notes regarding eslint-plugin-prettier to readme

packages/eslint-plugin-template/src/utils/create-eslint-rule.ts, packages/eslint-plugin/src/utils/create-eslint-rule.ts
Fixes https://github.com/angular-eslint/angular-eslint/issues/345
=> fix: add docs url for both plugins

lerna.json, package.json, packages/eslint-plugin-template/package.json, packages/eslint-plugin-template/src/rules/accessibility-alt-text.ts, packages/eslint-plugin-template/src/rules/accessibility-elements-content.ts, packages/eslint-plugin-template/src/rules/accessibility-label-for.ts, packages/eslint-plugin-template/src/rules/accessibility-table-scope.ts, packages/eslint-plugin-template/src/rules/accessibility-valid-aria.ts, packages/eslint-plugin-template/src/rules/banana-in-box.ts, packages/eslint-plugin-template/src/rules/click-events-have-key-events.ts, packages/eslint-plugin-template/src/rules/conditional-complexity.ts, packages/eslint-plugin-template/src/rules/cyclomatic-complexity.ts, packages/eslint-plugin-template/src/rules/mouse-events-have-key-events-rule.ts, packages/eslint-plugin-template/src/rules/no-any.ts, packages/eslint-plugin-template/src/rules/no-autofocus.ts, packages/eslint-plugin-template/src/rules/no-call-expression.ts, packages/eslint-plugin-template/src/rules/no-distracting-elements.ts, packages/eslint-plugin-template/src/rules/no-duplicate-attributes.ts, packages/eslint-plugin-template/src/rules/no-negated-async.ts, packages/eslint-plugin-template/src/rules/no-positive-tabindex.ts, packages/eslint-plugin-template/src/utils/attributes-comparator.ts, packages/eslint-plugin-template/src/utils/get-attribute-value.ts, packages/eslint-plugin-template/src/utils/is-interactive-element/index.ts, packages/eslint-plugin/package.json, yarn.lock
=> fix(eslint-plugin-template): conditional-complexity error from bundling

packages/builder/src/index.ts
=> fix(builder): printInfo should not be taken into account for report

packages/eslint-plugin-template/src/rules/i18n.ts, packages/eslint-plugin-template/tests/rules/i18n.test.ts
=> fix(eslint-plugin-template): i18n ignoreTags not being ignored properly

packages/eslint-plugin-template/src/rules/i18n.ts, packages/eslint-plugin-template/tests/rules/i18n.test.ts
=> fix(eslint-plugin-template): i18n reporting when a parent element already contains i18n id

README.md, package.json, packages/template-parser/jest.config.js, packages/template-parser/package.json, packages/template-parser/src/index.ts, packages/template-parser/tests/index.test.ts, packages/template-parser/tsconfig.json, yarn.lock
=> feat(template-parser): support eslint-disable comments in HTML templates

packages/eslint-plugin-template/src/rules/i18n.ts, packages/eslint-plugin-template/tests/rules/i18n.test.ts
=> fix(eslint-plugin-template): [i18n] remove unsafe fix

packages/eslint-plugin/src/index.ts
=> fix(eslint-plugin): correctly expose recommended--extra config

packages/schematics/src/utils.ts, packages/schematics/tests/convert-tslint-to-eslint/utils.test.ts
=> fix(schematics): support workspaces which use targets alias

packages/schematics/package.json, packages/schematics/src/add-eslint-to-project/index.ts, packages/schematics/src/add-eslint-to-project/schema.json, packages/schematics/src/collection.json, packages/schematics/src/convert-tslint-to-eslint/index.ts, packages/schematics/src/utils.ts, packages/schematics/tests/add-eslint-to-project/index.test.ts
This schematic will be required in v12 because there is no TSLint to convert OOTB.
=> feat(schematics): add add-eslint-to-project schematic

packages/eslint-plugin-template/src/rules/no-negated-async.ts
A single vertical line means it's a pipe in Angular.
=> fix(eslint-plugin-template): no-negated-async message tweak

packages/eslint-plugin-template/src/configs/all.json, packages/eslint-plugin-template/src/index.ts, packages/eslint-plugin-template/src/rules/eqeqeq.ts, packages/eslint-plugin-template/tests/rules/eqeqeq.test.ts
Relates to #202, #315 and #399.
~Waiting for #445 to mark it as ready for review.~
=> feat(eslint-plugin-template): add rule eqeqeq

packages/eslint-plugin-template/src/rules/accessibility-label-has-associated-control.ts, packages/schematics/src/migrations/update-12-0-0/update-12-0-0.ts, packages/schematics/tests/migrations/update-12-0-0/update-12-0-0.test.ts
1st. commit: adds information to the schema, missed in #392;
2nd. commit: migration from `accessibility-label-for` to `accessibility-label-has-associated-control`;
3rd. commit: migration for `eqeqeq`.
=> build: v12 migrations

packages/eslint-plugin-template/src/rules/no-negated-async.ts, packages/eslint-plugin-template/tests/rules/no-negated-async.test.ts
Reference: https://github.com/angular-eslint/angular-eslint/issues/280#issuecomment-760208638
The test is here just to ensure everything is ok. The fix was merged in #445.
=> test(eslint-plugin-template): [no-negated-async] add case with conditional

packages/eslint-plugin-template/tests/rules/conditional-complexity.test.ts
=> test(eslint-plugin-template): [conditional-complexity] add case with pipe

packages/eslint-plugin/src/rules/no-empty-lifecycle-method.ts, packages/eslint-plugin/src/utils/utils.ts, packages/eslint-plugin/tests/rules/no-empty-lifecycle-method.test.ts
Unfortunately the `fix` is not guaranteed, as someone may be calling it manually somewhere.
=> feat(eslint-plugin): [no-empty-lifecycle-method] add suggestion

packages/eslint-plugin-template/src/rules/i18n.ts, packages/eslint-plugin-template/tests/rules/i18n.test.ts
=> fix(eslint-plugin-template): [18n] ignore `checkAttributes` properly

packages/eslint-plugin/src/rules/no-host-metadata-property.ts, packages/eslint-plugin/src/utils/utils.ts, packages/eslint-plugin/tests/rules/no-host-metadata-property.test.ts
=> feat(eslint-plugin): [no-host-metadata-property] add option to allow static values

packages/schematics/src/ng-add/index.ts, packages/schematics/tests/ng-add/index.test.ts
=> feat(schematics): on `ng add` include a lint command if none exists

packages/builder/tests/index.test.ts
Hi, I was looking into contributing to this project but I encountered a problem while setting up the repo.
After a clone and install, there was one failing test on my Windows machine.
This PR fixes that test 🙂
=> test(builder): fix failing test under Windows

packages/eslint-plugin/src/rules/sort-ngmodule-metadata-arrays.ts, packages/eslint-plugin/tests/rules/sort-ngmodule-metadata-arrays.test.ts
=> feat(eslint-plugin): [sort-ngmodule-metadata-arrays] add fixer

.github/ISSUE_TEMPLATE/builder.md, .github/ISSUE_TEMPLATE/eslint-plugin-template.md, .github/ISSUE_TEMPLATE/eslint-plugin.md, .github/ISSUE_TEMPLATE/template-parser.md, .github/ISSUE_TEMPLATE/utils.md
While doing this, I also noticed that we could improve this by adding repro section, that includes configuration and use-case(s). WDYT?
=> docs: add more package versions in issues templates

packages/eslint-plugin/docs/rules/no-input-rename.md, packages/eslint-plugin/src/rules/no-input-rename.ts, packages/eslint-plugin/tests/rules/no-input-rename.test.ts
=> feat(eslint-plugin): [no-input-rename] add option to allow some inputs

README.md
remove one letter, very minor change in the docs. no code change
=> docs: change gets to get in readme.md

packages/eslint-plugin/src/rules/no-output-native.ts, packages/eslint-plugin/tests/rules/no-output-native.test.ts
=> fix(eslint-plugin): [no-output-native] correct false positives

packages/eslint-plugin-template/src/rules/no-autofocus.ts, packages/eslint-plugin-template/src/utils/get-dom-elements.ts, packages/eslint-plugin-template/src/utils/to-pattern.ts, packages/eslint-plugin-template/tests/rules/no-autofocus.test.ts
=> fix(eslint-plugin-template): [no-autofocus] ignore custom elements

packages/builder/src/lint.impl.spec.ts, packages/builder/src/lint.impl.ts, packages/builder/src/schema.d.ts, packages/builder/src/schema.json, packages/builder/src/utils/create-directory.ts
=> feat(builder): added outputFile option

packages/builder/src/lint.impl.spec.ts, packages/builder/src/schema.d.ts, packages/builder/src/schema.json, packages/builder/src/utils/eslint-utils.spec.ts, packages/builder/src/utils/eslint-utils.ts
=> feat(builder): add rulesdir option

packages/builder/src/lint.impl.spec.ts, packages/builder/src/schema.d.ts, packages/builder/src/schema.json, packages/builder/src/utils/eslint-utils.spec.ts, packages/builder/src/utils/eslint-utils.ts
=> feat(builder): add resolvePluginsRelativeTo option

package.json, packages/eslint-plugin-template/package.json, packages/eslint-plugin/package.json, packages/integration-tests/package.json, packages/integration-tests/tests/__snapshots__/v1123-multi-project-manual-config.test.ts.snap, packages/integration-tests/tests/__snapshots__/v1123-multi-project-yarn-auto-convert.test.ts.snap, packages/integration-tests/tests/__snapshots__/v1123-single-project-yarn-auto-convert.test.ts.snap, packages/integration-tests/tests/__snapshots__/v1123-strict-multi-project-auto-convert.test.ts.snap, packages/integration-tests/tests/__snapshots__/v12-new-workspace.test.ts.snap, packages/schematics/package.json, packages/schematics/tests/migrations/update-12-0-0/update-12-0-0.test.ts, packages/utils/package.json, yarn.lock
=> feat(schematics): better support @angular/cli 12.1

package.json, packages/eslint-plugin-template/docs/rules/accessibility-label-for.md, packages/eslint-plugin-template/docs/rules/accessibility-label-has-associated-control.md, packages/eslint-plugin-template/docs/rules/conditional-complexity.md, packages/eslint-plugin-template/docs/rules/cyclomatic-complexity.md, packages/eslint-plugin-template/docs/rules/i18n.md, packages/eslint-plugin-template/docs/rules/no-duplicate-attributes.md, packages/eslint-plugin-template/src/rules/accessibility-label-for.ts, packages/eslint-plugin-template/src/rules/conditional-complexity.ts, packages/eslint-plugin-template/src/rules/cyclomatic-complexity.ts, packages/eslint-plugin-template/src/rules/no-duplicate-attributes.ts, packages/eslint-plugin-template/src/utils/create-eslint-rule.ts, packages/eslint-plugin/docs/rules/component-class-suffix.md, packages/eslint-plugin/docs/rules/component-max-inline-declarations.md, packages/eslint-plugin/docs/rules/directive-class-suffix.md, packages/eslint-plugin/docs/rules/no-input-prefix.md, packages/eslint-plugin/docs/rules/no-input-rename.md, packages/eslint-plugin/docs/rules/pipe-prefix.md, packages/eslint-plugin/src/utils/create-eslint-rule.ts, tools/scripts/generate-rule-docs.ts
FYI @rafaelss95 
Now that things are in pretty good shape, this also updates the plugins to point at the docs for individual rules
=> docs: autogenerate default values as part of options description

packages/schematics/src/migrations/update-13-0-0/update-13-0-0.ts, packages/schematics/tests/migrations/update-13-0-0/update-13-0-0.test.ts
=> fix(schematics): auto update eslint-plugin-import as part of v13 ng update

packages/eslint-plugin/src/configs/README.md
there was a missing " after "off
=> chore: added missing " to the readme

packages/builder/package.json, yarn.lock
=> fix(builder): add explicit dependency on nx

packages/schematics/src/convert-tslint-to-eslint/convert-to-eslint-config.ts, packages/schematics/src/utils.ts, packages/schematics/tests/add-eslint-to-project/index.test.ts
=> fix(schematics): prefer sourceRoot if available for root project

packages/eslint-plugin-template/docs/rules/attributes-order.md, packages/eslint-plugin-template/src/rules/attributes-order.ts, packages/eslint-plugin-template/tests/rules/attributes-order/cases.ts
=> fix(eslint-plugin-template): [attributes-order] fixes for structural directives and "dotted" names

packages/nx-plugin/generators.json, packages/nx-plugin/src/generators/rule/files/src/rules/__name__.ts.template, packages/nx-plugin/src/generators/rule/files/src/rules/__ruleName__.ts.template, packages/nx-plugin/src/generators/rule/files/tests/cases.ts.template, packages/nx-plugin/src/generators/rule/files/tests/spec.ts.template, packages/nx-plugin/src/generators/rule/generator.spec.ts, packages/nx-plugin/src/generators/rule/generator.ts, packages/nx-plugin/src/generators/rule/schema.d.ts, packages/nx-plugin/src/generators/rule/schema.json
This pull request introduces an Nx generator to generate a skeleton for new lint rules.
=> feat: generator to generate skeleton for new lint rules

packages/eslint-plugin-template/docs/rules/attributes-order.md, packages/eslint-plugin-template/src/rules/attributes-order.ts, packages/eslint-plugin-template/tests/rules/attributes-order/cases.ts
=> fix(eslint-plugin-template): [attributes-order] Handle explicit ng-template usage

packages/template-parser/src/index.ts, packages/template-parser/tests/index.test.ts
=> fix(parser): do not error on @defer usage in Angular 17

packages/eslint-plugin/docs/rules/use-lifecycle-interface.md, packages/eslint-plugin/src/rules/use-lifecycle-interface.ts, packages/eslint-plugin/tests/rules/use-lifecycle-interface/cases.ts
Missing piece of #1691, I was unable to push to the PR
Applying as chore because it should have been part of the original commit and no need for it to be separate on the changelog
=> chore(eslint-plugin): add missing import as part of auto-fix

yarn.lock
Reverts angular-eslint/angular-eslint#1939
=> Revert "fix: update nrwl monorepo to v19.5.3"

packages/eslint-plugin-template/docs/rules/no-call-expression.md, packages/eslint-plugin-template/tests/rules/no-call-expression/cases.ts, packages/template-parser/src/index.ts, packages/template-parser/tests/index.test.ts, packages/test-utils/src/convert-annotated-source-to-failure-case.ts
Re-created due to https://github.com/angular-eslint/angular-eslint/pull/1887#issuecomment-2308874016
=> fix(template-parser): visit receiver of Call expression

e2e/src/__snapshots__/new-workspace-type-module.test.ts.snap, e2e/src/eslint-8--new-workspace-create-application-false-ng-add-then-project.test.ts, e2e/src/eslint-8--new-workspace-create-application-false-project-then-ng-add.test.ts, e2e/src/eslint-8--new-workspace.test.ts, e2e/src/new-workspace-type-module.test.ts, e2e/suites/9/project.json, e2e/utils/fixtures.ts, package.json, packages/builder/src/lint.impl.spec.ts, packages/builder/src/lint.impl.ts, packages/builder/src/utils/eslint-utils.spec.ts, packages/builder/src/utils/eslint-utils.ts, packages/schematics/src/ng-add/index.ts, packages/schematics/src/utils.ts, packages/schematics/tests/application/index.test.ts, packages/schematics/tests/utils.test.ts
=> feat: support ESM configs and .cjs and .mjs extensions

e2e/src/__snapshots__/eslint-8--inline-template-fixer.test.ts.snap, e2e/src/__snapshots__/eslint-8--new-workspace-create-application-false-ng-add-then-project.test.ts.snap, e2e/src/__snapshots__/eslint-8--new-workspace-create-application-false-project-then-ng-add.test.ts.snap, e2e/src/__snapshots__/eslint-8--new-workspace.test.ts.snap, e2e/src/__snapshots__/inline-template-fixer.test.ts.snap, e2e/src/__snapshots__/new-workspace-create-application-false-ng-add-then-project.test.ts.snap, e2e/src/__snapshots__/new-workspace-create-application-false-project-then-ng-add.test.ts.snap, e2e/src/__snapshots__/new-workspace-type-module.test.ts.snap, e2e/src/__snapshots__/new-workspace.test.ts.snap, package.json, packages/builder/package.json, packages/schematics/package.json, pnpm-lock.yaml
Update the Angular packages' versions to the stable 19.0.0.
=> feat: update angular packages to the stable v19

packages/angular-eslint/package.json
=> fix(angular-eslint): allow using angular-eslint with ng add and ng update

README.md
As v3 is now released, changing the wordings seems adapted.  
Also add the link to the plugin to avoid having to search the correct one.
=> docs(README.md): vsCode plugin recommendation

docs/CONFIGURING_FLAT_CONFIG.md
=> docs: Update CONFIGURING_FLAT_CONFIG.md

packages/eslint-plugin-template/docs/rules/no-interpolation-in-attributes.md, packages/eslint-plugin-template/src/rules/no-interpolation-in-attributes.ts, packages/eslint-plugin-template/tests/rules/no-interpolation-in-attributes/cases.ts
=> feat(eslint-plugin-template): [no-interpolation-in-attributes] add allowSubstringInterpolation option 

docs/MIGRATING_FROM_TSLINT.md
- fix `choose` typo in migration guide
- `pnpm pre-commit`
=> docs: fix choose typo

packages/eslint-plugin-template/docs/rules/prefer-at-empty.md, packages/eslint-plugin-template/src/rules/prefer-at-empty.ts, packages/eslint-plugin-template/tests/rules/prefer-at-empty/cases.ts
Fixes https://github.com/angular-eslint/angular-eslint/pull/2448#issuecomment-2907129494
=> fix(eslint-plugin-template): [prefer-at-empty] remove closing brace from @if when no longer needed

CLAUDE.md, packages/eslint-plugin-template/docs/rules/prefer-template-literal.md, packages/eslint-plugin-template/tests/rules/prefer-template-literal/cases.ts
=> chore(eslint-plugin-template): add test coverage for issue #2436
